# IPTV PROXY CACHE (location /px/)
location ~ ^/px/([^/]+)/(.*)$ {
    allow 181.63.176.21;
    allow 10.200.0.0/24;
    allow 127.0.0.1;
    deny all;

    resolver 127.0.0.1 valid=60s ipv6=off;
    set $backend_host $1;
    set $backend_path /$2$is_args$args;
    proxy_pass http://$backend_host$backend_path;

    proxy_set_header Host $backend_host;
    proxy_set_header User-Agent $http_user_agent;
    proxy_set_header Referer $http_referer;
    proxy_set_header Range $http_range;

    # Cache: hardcoded valid por codigo (no soporta variables)
    proxy_cache iptv_cache;
    proxy_cache_valid 200 206 60s;
    proxy_cache_valid 302 301 10s;
    proxy_cache_valid 404 10s;
    proxy_cache_lock on;
    proxy_cache_lock_timeout 15s;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    proxy_cache_background_update on;
    proxy_cache_revalidate on;
    # Bypass cache para .m3u8 (contenido dinamico — playlist cambia cada 2s)
    proxy_cache_bypass $arg_nocache;

    proxy_buffering on;
    proxy_buffer_size 32k;
    proxy_buffers 32 32k;
    proxy_busy_buffers_size 64k;

    proxy_connect_timeout 3s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;

    proxy_http_version 1.1;
    proxy_set_header Connection "";

    add_header X-Cache-Status $upstream_cache_status always;
}
