server:
    interface: 178.156.147.234
    interface: 127.0.0.1
    interface: 10.200.0.1
    port: 53
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    access-control: 127.0.0.1/32 allow
    access-control: 10.200.0.0/24 allow
    access-control: 181.63.176.21/32 allow
    access-control: 0.0.0.0/0 refuse
    hide-identity: yes
    hide-version: yes
    use-syslog: yes
    verbosity: 1
    cache-min-ttl: 60
    cache-max-ttl: 86400
    prefetch: yes
    prefetch-key: yes
    num-threads: 2
    msg-cache-size: 50m
    rrset-cache-size: 100m
    minimal-responses: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-referral-path: yes
    serve-expired: yes
    serve-expired-ttl: 3600
    edns-buffer-size: 1232


    # === DNS HIJACK IPTV HOSTS → VPS (2026-04-20) ===
    local-zone: "nfqdeuxu.x1megaott.online." redirect
    local-data: "nfqdeuxu.x1megaott.online. 60 IN A 178.156.147.234"
    local-zone: "line.tivi-ott.net." redirect
    local-data: "line.tivi-ott.net. 60 IN A 178.156.147.234"
    local-zone: "ky-tv.cc." redirect
    local-data: "ky-tv.cc. 60 IN A 178.156.147.234"
    local-zone: "tivigo.cc." redirect
    local-data: "tivigo.cc. 60 IN A 178.156.147.234"
    local-zone: "rynivorn.cc." redirect
    local-data: "rynivorn.cc. 60 IN A 178.156.147.234"
    local-zone: "zivovrix.cc." redirect
    local-data: "zivovrix.cc. 60 IN A 178.156.147.234"

forward-zone:
    name: "."
    forward-tls-upstream: no
    forward-first: yes
    forward-addr: 1.1.1.1
    forward-addr: 1.0.0.1
    forward-addr: 8.8.8.8
    forward-addr: 8.8.4.4
    forward-addr: 9.9.9.9

