#
# Use this configuration with WireGuard client
#
[Interface]
MTU = 1280
Table = off
Address = 10.14.0.2/16
PrivateKey = 0GSmDADZNB6ebE1vjxDN7eKZfUruLqtAkQLkM0qGekI=
PostUp = /opt/netshield/scripts/brazil-route-persist.sh
PostDown = /opt/netshield/scripts/brazil-route-cleanup.sh

[Peer]
PublicKey = IFTVXxhLEqVgZI/JGOPRtmrNUQW1DNljeBe8Ys7v90A=
AllowedIPs = 0.0.0.0/0
Endpoint = br-sao.prod.surfshark.com:51820
PersistentKeepalive = 25
