#
# Use this configuration with WireGuard client
#
[Interface]
MTU = 1280
Table = off
Address = 10.14.0.2/16
PrivateKey = mLgMo04gQ/XvFccW90JMoZuLGiiPxnI46Wte5cuLtn4=
PostUp = /opt/netshield/scripts/miami-route-persist.sh
PostDown = /opt/netshield/scripts/miami-route-cleanup.sh

[Peer]
PublicKey = KvJ/jtWb8BsBI85OcZnOIJu9kfh12mCMR4cejWFpDCc=
AllowedIPs = 0.0.0.0/0
Endpoint = us-mia.prod.surfshark.com:51820
PersistentKeepalive = 25
